"SQLNAME=trendRefreshFund"
UPDATE POOL_FUND SET STATUS={STATUS},HOLD={HOLD},HISTORY={HISTORY},EXPECT={EXPECT},LAST={LAST},TMR={TMR},BASE={BASE},VOLUMN5={VOLUMN5} WHERE CODE={CODE}

"SQLNAME=trendRefreshStock"
UPDATE POOL_STOCK SET STATUS={STATUS},HOLD={HOLD},HISTORY={HISTORY},EXPECT={EXPECT},LAST={LAST},TMR={TMR},BASE={BASE},VOLUMN5={VOLUMN5} WHERE CODE={CODE}

"SQLNAME=getPool"
SELECT * FROM <<table>> ORDER BY STATUS,VOLUMN5,HOLD

"SQLNAME=chart"
SELECT * FROM ASSET WHERE DT<={today}[ AND DT>={start}]

"SQLNAME=getRecords"
SELECT NAME,BUY,SELL,PROFIT FROM RECORDS WHERE SELL is not null ORDER BY SELL,BUY,PROFIT DESC

"SQLNAME=updateRecords"
UPDATE RECORDS SET  SELL={SELL},PROFIT={PROFIT} WHERE NAME={NAME} AND SELL is null

"SQLNAME=getHold"
SELECT * FROM POOL_STOCK WHERE NAME IN (SELECT NAME FROM RECORDS WHERE SELL is null)
UNION ALL
SELECT * FROM POOL_FUND WHERE NAME IN (SELECT NAME FROM RECORDS WHERE SELL is null)
ORDER BY TMR DESC

"SQLNAME=getDts"
SELECT DISTINCT DT FROM HISTORY_STOCK

"SQLNAME=getHistory"
SELECT DT,CODE,STATUS,RATE,NEXT_OPEN_RATE,VOLUMN5 FROM HISTORY_STOCK WHERE DT={DT}
UNION ALL
SELECT DT,CONCAT('F',CODE),STATUS,RATE,NEXT_OPEN_RATE,VOLUMN5 FROM HISTORY_FUND WHERE DT={DT}
ORDER BY STATUS,VOLUMN5

"SQLNAME=insertHistoryStock"
INSERT INTO HISTORY_STOCK VALUES({DT},{CODE},{STATUS},{RATE},{NEXT_OPEN_RATE},{VOLUMN5})

"SQLNAME=insertHistoryFund"
INSERT INTO HISTORY_FUND VALUES({DT},{CODE},{STATUS},{RATE},{NEXT_OPEN_RATE},{VOLUMN5})

"SQLNAME=getBestUpdate"
SELECT * FROM <<table>> WHERE FLAG is null